Revision improvements
calvinsID/azure-cli-extensions pull request #113
Opened 2022-05-23 20:05 UTC by haroonf

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2022-05-23 20:06 UTC, haroonf commented
work item: https://msazure.visualstudio.com/Antares/_sprints/taskboard/Antares%20CLI%20and%20PS/Antares/Antares%20CLI%20and%20PS/S212?workitem=14443198

2022-05-23 20:13 UTC, haroonf commented on src/containerapp/azext_containerapp/_utils.py
>  # required because what if .5, .5? We need sum to be 100, so can't round up or down both times
Remove the old _round function if it not used

2022-05-25 21:09 UTC, StrawnSC requested changes
In addition to the comments inline we should also do the following:
- Make sure the linter check passes (seems like it would fail since we didn't add help text for the new command) 
- Make sure the style check passes 
- Add some tests

2022-05-25 21:52 UTC, panchagnula commented on src/containerapp/azext_containerapp/_utils.py
> +    while (sys.getsizeof(json.dumps(traffic_def)) - sys.getsizeof("")) > 4096 and index < len(traffic_def):
Is there a reason we are doing this? Is the platform team not increasing the size of their PATCH API? Did some one specifically ask for this to be added from platform team?

2022-05-25 21:53 UTC, panchagnula commented on src/containerapp/azext_containerapp/_utils.py
> +        raise ValidationError("Traffic size request cannot exceed 4096Bytes.")
I don't this is useful message - since the users won't know what to do with this Validation error? I would rather let API fail & add let API team know how many failures are actually occurring with this so they can fix the issue on their end, instead of hiding the problem & having users open issues on CLI.

2022-05-25 21:54 UTC, haroonf commented on src/containerapp/azext_containerapp/_utils.py
> +    while (sys.getsizeof(json.dumps(traffic_def)) - sys.getsizeof("")) > 4096 and index < len(traffic_def):
Just wrote a util in case it becomes necessary in the future, not being used currently.

2022-05-25 22:16 UTC, StrawnSC commented on src/containerapp/azext_containerapp/custom.py
> +    # _update_traffic_size(containerapp_def)
We should remove this comment

2022-05-27 18:29 UTC, merged