fix cert uploading issues
calvinsID/azure-cli-extensions pull request #141
Opened 2022-08-04 17:11 UTC by lil131

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2022-08-04 17:15 UTC, lil131 commented
1. fixing the issue that cert uploading failed on CLI but succeeded on portal
2. fixing the bug where replacing invalid characters in cert names failed
3. removing the test case for .pem cert uploading for now, as the api doesn't support .pem certs yet, and a private key validation was added to the api recently which will lead to the "Certificate must contain one private key." error for .pem certs.

2022-08-10 18:17 UTC, StrawnSC requested changes
Looks like there's a small merge conflict that needs to be fixed before we can merge

2022-08-10 18:17 UTC, StrawnSC commented
Also, @lil131 can you link the GitHub issue(s) that are related to this fix?

2022-08-11 20:35 UTC, StrawnSC approved these changes

2022-08-11 23:44 UTC, merged