4/26 release -- Up with --repo/--browse, exec (ssh) command, replica commands, log streaming commands
calvinsID/azure-cli-extensions pull request #72
Opened 2022-04-21 02:30 UTC by StrawnSC

---
Mostly done just the following minor changes + more testing 

- set output for up (according to @panchagnula's email)
- remove token from URL params for exec & logstream 
- rename logstreaming command 
- Set log stream --tail default value to 20 
- fix any style / linter issues 

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2022-04-21 08:08 UTC, StrawnSC commented
@haroonf this still has a bit more work to go but the major refactors are pretty much done (so you shouldn't get major merge conflicts if you need to start making some changes to up) 

I still have to test some more (mainly --repo and --source). There's a known issue I need to fix with --repo and I haven't really tested with --source yet. 

I also haven't fixed the style and there are a lot of style issues :( 

[btw I didn't end up separating out the code paths for --repo/--source/--image in their own methods since the logic indeed is pretty much the same]

2022-04-21 17:45 UTC, calvinsID commented
> @calvinsID can you add @panchagnula as a contributor to the repo? It won't let me add her as a reviewer

Added! Pending Sisira accepting

2022-04-21 18:34 UTC, panchagnula commented on src/containerapp/HISTORY.rst
> +0.4.0
I would like to keep this to 0.3.2

2022-04-21 18:36 UTC, panchagnula commented on src/containerapp/azext_containerapp/_archive_utils.py
> +# --------------------------------------------------------------------------------------------
Curious with the name of the file archive?

2022-04-21 18:47 UTC, panchagnula commented on src/containerapp/azext_containerapp/_clients.py
> +            PREVIEW_API_VERSION)
For the new commands or changes can we use the stable api-version, so we don't need to migrate this before GA release.

2022-04-21 18:50 UTC, panchagnula commented on src/containerapp/azext_containerapp/_clients.py
> +            PREVIEW_API_VERSION)
same comment on the api-version here

2022-04-21 18:53 UTC, panchagnula commented on src/containerapp/azext_containerapp/_help.py
> +    short-summary: Manage container app replicas (pods)
i believe replicas is a copy of pods - so lets remove (pods) from the help. Ignore my comment if the help text was provided by PMs of ACA.

2022-04-21 18:54 UTC, panchagnula commented on src/containerapp/azext_containerapp/_help.py
> +    short-summary: Show past logs and/or print logs in real time (with the --follow parameter). Note that the logs are only taken from one revision, replica (pod), and container.
same comment abt (pod)

2022-04-21 18:55 UTC, panchagnula commented on src/containerapp/azext_containerapp/_help.py
> +    short-summary: Show a container app replica (pod)
same comment (pod) :)

2022-04-21 18:56 UTC, panchagnula commented on src/containerapp/azext_containerapp/_params.py
> +        c.argument('replica', help="The name of the replica (pod) to ssh into. List replicas with 'az containerapp replica list'. A replica may not exist if there is not traffic to your app.")
same comment on (pod)

2022-04-21 19:04 UTC, panchagnula commented on src/containerapp/azext_containerapp/_params.py
> +        c.argument('replica', help="The name of the replica (pod). List replicas with 'az containerapp replica list'. A replica may not exist if there is not traffic to your app.")
same comment on (pod)

2022-04-21 19:05 UTC, panchagnula commented on src/containerapp/azext_containerapp/_params.py
> +        # c.argument('image', type=str, options_list=['--image', '-i'], help="Container image, e.g. publisher/image-name:tag.")
any reason this is commented out - just delete it if this not needed?

2022-04-21 19:09 UTC, panchagnula commented on src/containerapp/azext_containerapp/_params.py
> +        c.argument('dryrun', help="Show summary of the operation instead of executing it.")
remove dry run & when used this should be dry-run

2022-04-21 19:11 UTC, panchagnula commented on src/containerapp/azext_containerapp/_params.py
> +        c.argument('managed_env', configured_default='managed_env')
Rename to environment this should match the arguments used in create, so if a user set global config for this, it will work across all comments https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest

2022-04-21 20:04 UTC, panchagnula commented on src/containerapp/azext_containerapp/_utils.py
> +                    logger.warning('  Role assignment creation failed.\n')
why is this not error & just warning? 
In our case when SP creation fails, we should provide the action items as well, to may be re-try with the CLI command to create SP themselves?

2022-04-21 20:05 UTC, panchagnula commented on src/containerapp/azext_containerapp/_utils.py
> +def await_github_action(cmd, token, repo, branch, name, resource_group_name, timeout=300):
is the timeout is Sec or ms? can you make this clear by naming the argument to reflect the units?

2022-04-21 20:06 UTC, panchagnula commented on src/containerapp/azext_containerapp/_utils.py
> +            raise CLIInternalError("The Github Action creation failed.")
Is there a way to surface the reason for failure?

2022-04-21 20:59 UTC, StrawnSC commented on src/containerapp/azext_containerapp/_archive_utils.py
> +# --------------------------------------------------------------------------------------------
I didn't add this. @haroonf is this from your branch?

2022-04-21 21:00 UTC, StrawnSC commented on src/containerapp/azext_containerapp/_params.py
> +        c.argument('dryrun', help="Show summary of the operation instead of executing it.")
dry run support has been removed already. I'll remove this as well.

2022-04-21 21:21 UTC, StrawnSC commented on src/containerapp/azext_containerapp/_params.py
> +        c.argument('managed_env', configured_default='managed_env')
The argument name exposed to the user in this case is still `--environment`: 

<img width="906" alt="Screen Shot 2022-04-21 at 2 20 28 PM" src="https://user-images.githubusercontent.com/10121214/164554266-730291cb-229e-459c-bca2-e248cbe4b4b3.png">


The function argument name is `managed_env` (for all container apps commands), but the user inputs it as `--environment`
<img width="906" alt="Screen Shot 2022-04-21 at 2 18 28 PM" src="https://user-images.githubusercontent.com/10121214/164553954-767ea31b-5a89-4a4f-88de-35d3c857cf25.png">

2022-04-21 21:22 UTC, StrawnSC commented on src/containerapp/azext_containerapp/_utils.py
> +                    logger.warning('  Role assignment creation failed.\n')
It does error out in this case (note the `raise` on the following line)

2022-04-21 21:25 UTC, StrawnSC commented on src/containerapp/azext_containerapp/_utils.py
> +            raise CLIInternalError("The Github Action creation failed.")
The API response doesn't include a longer description besides the status. I'll double check with Sanchit and see if there's some other API we can call

2022-04-21 21:25 UTC, StrawnSC commented on src/containerapp/azext_containerapp/_utils.py
> +def await_github_action(cmd, token, repo, branch, name, resource_group_name, timeout=300):
It's seconds (5 minute timeout). I'll update the parameter name

2022-04-22 16:44 UTC, panchagnula commented on src/containerapp/HISTORY.rst
> +* Create or update a container app and all associated resources (container app environment, ACR, Github Actions, resource group, etc.) with 'az containerapp up'
Nit - line 8 have az containerapp up in the beginning of the sentence so it easily reflects what the change is instead of having to read the full sentence. Initial read seems like there is some update on create & update commands.

2022-04-22 16:45 UTC, panchagnula commented on src/containerapp/azext_containerapp/.flake8
> +ignore =
This is limited to our extension only but might be something core-cli might push back on & might have to be removed. (Can leave it for now)

2022-04-22 16:47 UTC, panchagnula commented on src/containerapp/azext_containerapp/_archive_utils.py
> +# --------------------------------------------------------------------------------------------
if these methods are used - please rename the file, to reflect what this utils is for?

2022-04-22 16:50 UTC, panchagnula commented on src/containerapp/azext_containerapp/_clients.py
> +        api_version = STABLE_API_VERSION
@calvinsID this might already change the Update command? don't think this was part of your change - can you take a look as well & merge your changes as well :)

2022-04-22 17:00 UTC, panchagnula commented on src/containerapp/azext_containerapp/custom.py
> +def open_containerapp_in_browser(cmd, name, resource_group_name):
What happens in the case the app doesn't have FQDN?

2022-04-22 17:01 UTC, panchagnula commented on src/containerapp/azext_containerapp/_help.py
> +          az containerapp up -n MyContainerapp --repo https://github.com/myAccount/myRepo
also add an example for using with environment & --ingress + target port especially for --image

2022-04-22 18:11 UTC, calvinsID commented on src/containerapp/azext_containerapp/_clients.py
> +        api_version = STABLE_API_VERSION
I can add my changes after this PR goes through, since this is a big one

2022-04-22 18:16 UTC, calvinsID commented on src/containerapp/azext_containerapp/_clients.py
> +        elif r.status_code == 202:
Was there a change in the status code API is returning, or is this fixing a previous bug?

2022-04-22 18:17 UTC, calvinsID commented on src/containerapp/azext_containerapp/_archive_utils.py
> +        raise CLIError("Failed to get a SAS URL to upload context. Error: {}".format(e.message))
Nit: Core CLI requires specific error types to be raised (ex. ValidationError) I'm not sure if extensions has the same requirement but would be good to use specific error types

2022-04-22 18:19 UTC, haroonf commented on src/containerapp/azext_containerapp/_clients.py
> +        elif r.status_code == 202:
API returns 202, not sure if this is a bug or a new version thing

2022-04-22 19:34 UTC, calvinsID commented on src/containerapp/azext_containerapp/_clients.py
> +        elif r.status_code == 202:
Thanks!

2022-04-22 19:35 UTC, calvinsID commented on src/containerapp/azext_containerapp/_clients.py
> +        api_version = STABLE_API_VERSION
I've just tested the change to use the PATCH api, and works as expected - no impact to current behaviour

2022-04-22 19:41 UTC, panchagnula commented on src/containerapp/azext_containerapp/_archive_utils.py
> +        raise CLIError("Failed to get a SAS URL to upload context. Error: {}".format(e.message))
+1 to this - I am very sure core-cli will call this out.

2022-04-22 19:44 UTC, panchagnula commented on src/containerapp/azext_containerapp/_clients.py
> +        api_version = STABLE_API_VERSION
Thanks for confirming

2022-04-22 21:26 UTC, panchagnula requested changes
@haroonf please update/ resolve active comments , so we can merge & start a new PR to  main. Thanks!

2022-04-22 22:58 UTC, merged